### ISSUE TITLE
a new spack leads to a full rebuild

### ISSUE THREAD

**Issue by dguibert** [flatironinstitute/nixpack#42]
When nixpack is rebuild with a new spack (as an updated repository), this leads to a full rebuild of all the packages.

This is indeed the way the nix package manager works, the inputs of the functions have changed so the outputs are recomputed.

Maybe we could think of separating the spack repository in two parts:
1. the lib (spack/lib/spack)
2. the builtin repo (spack/var/spack/repos/builtin)

Then the funciton `spackBuilder` may also get rid of:
- `repos` (only when `withRepos = true`)
- `spackCache` (does not seem to be required already, setting it to null allow nixpack to build packages "as usual")

At last, modules.nix may need to be adapted to this split, as for now it requires `withRepos=true`.

Avoiding full rebuilds when introducing a new package or fixing an existing one may offer better user experience (or at least avoid switching back to spack only during the process)

**Comment by dylex** [comment]
This is indeed something that's been annoying us for a while.  I started working on this last month and immediately ran into some spack bugs where it's not properly preserving repo files.  I managed to fix those issues such that things would build, but then I realized there's still a complication of how you actually reference the separate spack "builtin" repo.  If you have nix check it out from a git repo and keep it in the nix store, you end up with the same problem because whenever you change the revesion, you get a new path to the repo, so everything is treated as having changed (since the whole repo is still an input to the spack build).  The thing we've been doing with the separate nixpack fi/repo actually works pretty well build-wise, because the inputs are fixed "local" files not coming out of nix, but it makes it annoying to update spack packages.

Effectively to fix this I think individual spack packges would have to be treated as fixed-ouput derivations somehow, so their hash depend only on their contents, not where they're sourced from, but I don't know a good way to make this happen. The new `__contentAddressed` feature would allow this.

**Comment by dylex** [comment]
I guess the other obvious solution is to let users point to their own spack checkout, for example as a git submodule, and reference individual files, so that it all becomes content-addressed, but then users have to manage revisions themselves for reproducible builds.

**Comment by dguibert** [comment]
I've have this patch https://github.com/dguibert/nixpack/commit/9f4c37c369d34f35c9eff739752d44f207b9218e to isolate the content of `repo.yaml` and the directory of a package (`package.py` and its patches) from the spack repo.

But the derivation was still depending on the Spack repo as it depends on `spackCache`.
I'll try with `spackCache=null`...

**Comment by dguibert** [comment]
The PR #43 has been merged.
